version: "3.5"
services:
   rabbitmq:
      image: rabbitmq:3.7-management
      container_name: rabbitmq-container
#      user: rabbitmq
      restart: always
      ports:
         - 5672:5672
         - 15672:15672
      volumes:
         - ./rabbitmq/data:/var/lib/rabbitmq:rw
         - ./rabbitmq/definitions.json:/etc/rabbitmq/definitions.json:ro
         - ./rabbitmq/rabbitmq.config:/etc/rabbitmq/rabbitmq.config:ro
      networks:
         - elk-net
   logstash:
      depends_on:
         - elasticsearch
         - rabbitmq
      #image: docker.elastic.co/logstash/logstash-oss:6.2.4
      image: docker.elastic.co/logstash/logstash:6.8.5
      container_name: logstash-container
      user: logstash
      restart: always
      volumes:
         - ./logstash/logstash.conf:/usr/share/logstash/pipeline/logstash.conf:ro
         - ./logstash/logstash.conf:/usr/share/logstash/templates/workflow-events.json:ro
      ports:
         - 9600:9600
      networks:
         - elk-net
   elasticsearch:
      image: docker.elastic.co/elasticsearch/elasticsearch-oss:6.2.4
      container_name: elasticsearch-container
      user: elasticsearch
      restart: always
      environment:
         - discovery.type=single-node
         - cluster.name=elasticsearch-cluster
         - node.name=elasticsearch-node-1
         - bootstrap.memory_lock=true
         - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      ulimits:
         memlock:
            soft: -1
            hard: -1
      volumes:
         - ./elasticsearch/data:/usr/share/elasticsearch/data:rw
      ports:
         - 9200:9200
      networks:
         - elk-net
   kibana:
      depends_on:
         - elasticsearch
      image: docker.elastic.co/kibana/kibana-oss:6.2.4
      container_name: kibana-container
      user: kibana
      restart: always
      environment:
         - ELASTICSEARCH_URL=http://elasticsearch-container:9200 
      volumes:
         - ./kibana/data:/usr/share/kibana/data:rw
      ports:
         - 5601:5601
      networks:
         - elk-net
   grafana:
      depends_on:
         - elasticsearch
      image: grafana/grafana:latest
      container_name: grafana-container
      user: grafana
      restart: always
      environment:
         - GF_SECURITY_ADMIN_PASSWORD=dibbs
         - GF_INSTALL_PLUGINS=grafana-piechart-panel,farski-blendstat-panel,mtanda-histogram-panel,blackmirror1-singlestat-math-panel
      volumes:
         - ./grafana/data:/var/lib/grafana:rw
         - ./grafana/dashboards:/etc/grafana/provisioning/dashboards:rw
         - ./grafana/datasources:/etc/grafana/provisioning/datasources:rw
      ports:
         - 3000:3000
      networks:
         - elk-net
networks:
   elk-net:
      name: elk-net
      driver: bridge
