{
 "title": "Main",
 "description": "Workflow Statistics. Drill down to a specific workflow by adjust provided parameters starting from left to right.",
 "time": { "from": "2019-12-01T00:00:00.000Z", "to": "2019-12-31T23:59:00.000Z" },
 "templating": {
  "list": [
   {
    "name": "bin_size",
    "query": "1m,10m,30m,1h,6h,12h,1d,7d,14d,30d"
   },
   {
    "name": "pegasus_version",
    "label": "pegasus-version",
    "query": "{\"find\": \"terms\", \"field\": \"pegasus_version.keyword\", \"query\": \"*\"}"
   },
   {
    "name": "submit_host",
    "query": "{\"find\": \"terms\", \"field\": \"submit_hostname.keyword\", \"query\": \"pegasus_version:$pegasus_version\"}"
   },
   {
    "name": "user",
    "query": "{\"find\": \"terms\", \"field\": \"user.keyword\", \"query\": \"submit_hostname:$submit_host AND pegasus_version:$pegasus_version\"}"
   },
   {
    "name": "root_workflow_id",
    "query": "{\"find\": \"terms\", \"field\": \"root_xwf_id.keyword\", \"query\":\"pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user\"}"
   },
   {
    "name": "submit_directory",
    "query": "{\"find\": \"terms\", \"field\": \"submit_dir.keyword\", \"query\":\"pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id\"}"
   },
   {
    "name": "dax_label",
    "query": "{\"find\": \"terms\", \"field\": \"dax.keyword\", \"query\": \"submit_dir.keyword:$submit_directory AND root_xwf_id:$root_workflow_id AND user:$user AND submit_hostname:$submit_host AND pegasus_version:$pegasus_version\"}"
   }
  ]
 },
 "panels": [
  {
   "title": "Users",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 0 },
   "format": "none",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "user.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "cardinality"
      }
     ],
     "query": "pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jobs",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "xwf__id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "pegasus_version$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Workflows",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 0 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "3650d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "root_xwf_id.keyword",
       "id": "1",
       "meta": {},
       "settings": { "precision_threshold": 40000 },
       "type": "cardinality"
      }
     ],
     "query": "pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": " ",
   "type": "text",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 0 },
   "content": "<div style=\"text-align: center;\">\n<!-- <h1>Pegasus Workflow Statistics</h1> -->\n\n<p >Select each of the above variables starting from left to \n    right to drill down to a specific workflow.\n</p>\n\n<table align=\"center\">\n  <tr>\n    <th>Options</th>\n    <th>Description</th>\n  </tr>\n  <tr>\n    <td><strong>pegasus_version</strong></td> \n    <td>the pegasus version(s) used to submit the workflow(s)</td>\n  </tr>\n  <tr>\n    <td><strong>submit_host</strong></td> \n    <td>the host(s) on which the workflow(s) was submitted</td>\n  </tr>\n  <tr>\n    <td><strong>user</strong></td>\n    <td>the user(s) who submitted the workflow(s)</td>\n  </tr>\n  <tr>\n    <td><strong>submit_directory</strong></td> \n    <td>the directory from which the workflow was submitted</td>\n  </tr>\n  <tr>\n    <td><strong>dax_label</strong></td>\n    <td>the workflow label</td>\n  </tr>\n</table>\n</div>\n\n"
  },
  {
   "title": "Integrity Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 4 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "xwf__id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "int_error_count:>0 AND submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Job Failures",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 4, "y": 4 },
   "format": "locale",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "xwf__id.keyword",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "exitcode:>0 AND submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Cumulative Walltime",
   "type": "singlestat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 4 },
   "format": "dtdurations",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "local_dur",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jobs Finishing (top 50)",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 8 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "root_xwf_id.keyword",
       "id": "3",
       "settings": {
        "min_doc_count": 1,
        "missing": null,
        "order": "desc",
        "orderBy": "_count",
        "size": "50"
       },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "CPU Models Used",
   "type": "grafana-piechart-panel",
   "description": "The different types of CPUs used to run workflow jobs. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 8 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cpu_model.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Job Duration Distribution",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short", "label": "Frequency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "local_dur",
       "id": "3",
       "settings": { "interval": 400, "min_doc_count": 1 },
       "type": "histogram"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Walltime Per CPU Model",
   "type": "grafana-piechart-panel",
   "description": "The different types of CPUs used to run workflow jobs. ",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 14 },
   "format": "short",
   "valueName": "total",
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "cpu_model.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "local_dur",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "sum"
      }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Filter Rate Per Core",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 20 },
   "yaxes": [
    { "format": "short", "label": "Frequency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "metadata_filter_rate_per_core",
       "id": "3",
       "settings": { "interval": 0.5, "min_doc_count": 1 },
       "type": "histogram"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Fraction of Time Doing Setup Operations",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 26 },
   "yaxes": [
    { "format": "short", "label": "Frequency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "metadata_setup_time_fraction",
       "id": "3",
       "settings": { "interval": 0.05, "min_doc_count": 1 },
       "type": "histogram"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Templates Per Core",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 12, "y": 28 },
   "yaxes": [
    { "format": "short", "label": "Frequency" }
   ],
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "metadata_templates_per_core",
       "id": "3",
       "settings": { "interval": 200, "min_doc_count": 1 },
       "type": "histogram"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "30d", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Jobs Success/Failures",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 37 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "alias": "Failed",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "exitcode:>0 AND  submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    },
    {
     "alias": "Successful",
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "exitcode:0 AND submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Average Job Duration",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 12, "y": 37 },
   "yaxes": [
    { "format": "s" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "local_dur",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "avg"
      }
     ],
     "query": "submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Integrity Failures",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 43 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "bucketAggs": [
      { "field": "@timestamp", "id": "2", "settings": { "interval": "$bin_size", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      { "field": "select field", "id": "1", "type": "count" }
     ],
     "query": "int_error_count:>0 AND submit_hostname:$submit_host AND user:$user AND pegasus_version:$pegasus_version AND submit_hostname:$submit_host AND user:$user AND root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory AND dax:$dax_label",
     "timeField": "@timestamp"
    }
   ]
  },
  {
   "title": "Workflows With Integrity Failures",
   "type": "table",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 50 },
   "targets": [
    {
     "bucketAggs": [
      {
       "fake": true,
       "field": "submit_hostname.keyword",
       "id": "4",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "user.keyword",
       "id": "5",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      {
       "fake": true,
       "field": "submit_dir.keyword",
       "id": "3",
       "settings": { "min_doc_count": 1, "order": "desc", "orderBy": "_count", "size": "0" },
       "type": "terms"
      },
      { "field": "@timestamp", "id": "2", "settings": { "interval": "1y", "min_doc_count": 0, "trimEdges": 0 }, "type": "date_histogram" }
     ],
     "metrics": [
      {
       "field": "int_error_count",
       "id": "1",
       "meta": {},
       "settings": {},
       "type": "count"
      }
     ],
     "query": "int_error_count:>0 AND  user:$user AND pegasus_version:$pegasus_version AND (submit_hostname:$submit_host OR submit__hostname:$submit_host) AND  root_xwf_id:$root_workflow_id AND submit_dir:$submit_directory",
     "timeField": "@timestamp"
    }
   ]
  }
 ]
}