apiVersion: 1

datasources:
  - name: Elasticsearch
    type: elasticsearch
    access: proxy
    database: "[pegasus-composite-events-]YYYY.MM"
    url: http://elasticsearch-container:9200
    isDefault: true
    jsonData:
      interval: Monthly
      timeField: "@timestamp"
      esVersion: 60
  
