apiVersion: 1

datasources:
  - name: ElasticStampede
    type: elasticsearch
    access: proxy
    database: "workflow-events-*"
    url: http://elasticsearch-container:9200
    jsonData:
      timeField: "@timestamp"
      esVersion: 70
  
